// AUTO-GENERATED by scripts/buildGeoDb.mjs
// Do not edit by hand.

export const BULK_CITY_COORDS = {
  "Aleppo, SY": {
    "lat": 36.2021,
    "lon": 37.1343
  },
  "Rostock, DE": {
    "lat": 54.0924,
    "lon": 12.0991
  },
  "Dortmund, DE": {
    "lat": 51.5136,
    "lon": 7.4653
  },
  "Paris, FR": {
    "lat": 48.8566,
    "lon": 2.3522
  },
  "Madrid, ES": {
    "lat": 40.4168,
    "lon": -3.7038
  },
  "New York, US": {
    "lat": 40.7128,
    "lon": -74.006
  },
  "Toronto, CA": {
    "lat": 43.6532,
    "lon": -79.3832
  },
  "Los Angeles, US": {
    "lat": 34.0522,
    "lon": -118.2437
  },
  "London, GB": {
    "lat": 51.5074,
    "lon": -0.1278
  },
  "Berlin, DE": {
    "lat": 52.52,
    "lon": 13.405
  },
  "Rome, IT": {
    "lat": 41.9028,
    "lon": 12.4964
  },
  "Amsterdam, NL": {
    "lat": 52.3676,
    "lon": 4.9041
  },
  "Warsaw, PL": {
    "lat": 52.2297,
    "lon": 21.0122
  },
  "Prague, CZ": {
    "lat": 50.0755,
    "lon": 14.4378
  },
  "Vienna, AT": {
    "lat": 48.2082,
    "lon": 16.3738
  },
  "Budapest, HU": {
    "lat": 47.4979,
    "lon": 19.0402
  },
  "Stockholm, SE": {
    "lat": 59.3293,
    "lon": 18.0686
  },
  "Oslo, NO": {
    "lat": 59.9139,
    "lon": 10.7522
  },
  "Copenhagen, DK": {
    "lat": 55.6761,
    "lon": 12.5683
  },
  "Helsinki, FI": {
    "lat": 60.1699,
    "lon": 24.9384
  },
  "Lisbon, PT": {
    "lat": 38.7223,
    "lon": -9.1393
  },
  "Athens, GR": {
    "lat": 37.9838,
    "lon": 23.7275
  },
  "Dublin, IE": {
    "lat": 53.3498,
    "lon": -6.2603
  },
  "Brussels, BE": {
    "lat": 50.8503,
    "lon": 4.3517
  },
  "Zurich, CH": {
    "lat": 47.3769,
    "lon": 8.5417
  },
  "Munich, DE": {
    "lat": 48.1351,
    "lon": 11.582
  },
  "Hamburg, DE": {
    "lat": 53.5511,
    "lon": 9.9937
  },
  "Frankfurt, DE": {
    "lat": 50.1109,
    "lon": 8.6821
  },
  "Cologne, DE": {
    "lat": 50.9375,
    "lon": 6.9603
  },
  "Barcelona, ES": {
    "lat": 41.3851,
    "lon": 2.1734
  },
  "Milan, IT": {
    "lat": 45.4642,
    "lon": 9.19
  },
  "Naples, IT": {
    "lat": 40.8518,
    "lon": 14.2681
  },
  "Turin, IT": {
    "lat": 45.0703,
    "lon": 7.6869
  },
  "Lyon, FR": {
    "lat": 45.764,
    "lon": 4.8357
  },
  "Marseille, FR": {
    "lat": 43.2965,
    "lon": 5.3698
  },
  "Toulouse, FR": {
    "lat": 43.6047,
    "lon": 1.4442
  },
  "Nice, FR": {
    "lat": 43.7102,
    "lon": 7.262
  },
  "Bordeaux, FR": {
    "lat": 44.8378,
    "lon": -0.5792
  },
  "Lille, FR": {
    "lat": 50.6292,
    "lon": 3.0573
  },
  "Antwerp, BE": {
    "lat": 51.2213,
    "lon": 4.4052
  },
  "Rotterdam, NL": {
    "lat": 51.9244,
    "lon": 4.4777
  },
  "The Hague, NL": {
    "lat": 52.0705,
    "lon": 4.3007
  },
  "Utrecht, NL": {
    "lat": 52.0907,
    "lon": 5.1214
  },
  "Ghent, BE": {
    "lat": 51.0543,
    "lon": 3.7174
  },
  "Bruges, BE": {
    "lat": 51.2093,
    "lon": 3.2247
  },
  "Porto, PT": {
    "lat": 41.1579,
    "lon": -8.6291
  },
  "Seville, ES": {
    "lat": 37.3891,
    "lon": -5.9845
  },
  "Valencia, ES": {
    "lat": 39.4699,
    "lon": -0.3763
  },
  "Bilbao, ES": {
    "lat": 43.263,
    "lon": -2.935
  },
  "Malaga, ES": {
    "lat": 36.7213,
    "lon": -4.4213
  },
  "Granada, ES": {
    "lat": 37.1773,
    "lon": -3.5986
  },
  "Krakow, PL": {
    "lat": 50.0647,
    "lon": 19.945
  },
  "Wroclaw, PL": {
    "lat": 51.1079,
    "lon": 17.0385
  },
  "Gdansk, PL": {
    "lat": 54.352,
    "lon": 18.6466
  },
  "Poznan, PL": {
    "lat": 52.4064,
    "lon": 16.9252
  },
  "Lodz, PL": {
    "lat": 51.7592,
    "lon": 19.456
  },
  "Szczecin, PL": {
    "lat": 53.4289,
    "lon": 14.553
  },
  "Bucharest, RO": {
    "lat": 44.4268,
    "lon": 26.1025
  },
  "Cluj-Napoca, RO": {
    "lat": 46.7712,
    "lon": 23.6236
  },
  "Timisoara, RO": {
    "lat": 45.7489,
    "lon": 21.2087
  },
  "Sofia, BG": {
    "lat": 42.6977,
    "lon": 23.3219
  },
  "Plovdiv, BG": {
    "lat": 42.1354,
    "lon": 24.7453
  },
  "Belgrade, RS": {
    "lat": 44.7866,
    "lon": 20.4489
  },
  "Zagreb, HR": {
    "lat": 45.815,
    "lon": 15.9819
  },
  "Ljubljana, SI": {
    "lat": 46.0569,
    "lon": 14.5058
  },
  "Bratislava, SK": {
    "lat": 48.1486,
    "lon": 17.1077
  },
  "Kyiv, UA": {
    "lat": 50.4501,
    "lon": 30.5234
  },
  "Lviv, UA": {
    "lat": 49.8397,
    "lon": 24.0297
  },
  "Odessa, UA": {
    "lat": 46.4825,
    "lon": 30.7233
  },
  "Kharkiv, UA": {
    "lat": 49.9935,
    "lon": 36.2304
  },
  "Minsk, BY": {
    "lat": 53.9045,
    "lon": 27.5615
  },
  "Vilnius, LT": {
    "lat": 54.6872,
    "lon": 25.2797
  },
  "Riga, LV": {
    "lat": 56.9496,
    "lon": 24.1052
  },
  "Tallinn, EE": {
    "lat": 59.437,
    "lon": 24.7536
  },
  "Reykjavik, IS": {
    "lat": 64.1466,
    "lon": -21.9426
  },
  "Glasgow, GB": {
    "lat": 55.8642,
    "lon": -4.2518
  },
  "Edinburgh, GB": {
    "lat": 55.9533,
    "lon": -3.1883
  },
  "Manchester, GB": {
    "lat": 53.4808,
    "lon": -2.2426
  },
  "Birmingham, GB": {
    "lat": 52.4862,
    "lon": -1.8904
  },
  "Liverpool, GB": {
    "lat": 53.4084,
    "lon": -2.9916
  },
  "Leeds, GB": {
    "lat": 53.8008,
    "lon": -1.5491
  },
  "Sheffield, GB": {
    "lat": 53.3811,
    "lon": -1.4701
  },
  "Bristol, GB": {
    "lat": 51.4545,
    "lon": -2.5879
  },
  "Newcastle upon Tyne, GB": {
    "lat": 54.9783,
    "lon": -1.6178
  },
  "Nottingham, GB": {
    "lat": 52.9548,
    "lon": -1.1581
  },
  "Southampton, GB": {
    "lat": 50.9097,
    "lon": -1.4044
  },
  "Cardiff, GB": {
    "lat": 51.4816,
    "lon": -3.1791
  },
  "Belfast, GB": {
    "lat": 54.5973,
    "lon": -5.9301
  },
  "Chicago, US": {
    "lat": 41.8781,
    "lon": -87.6298
  },
  "Houston, US": {
    "lat": 29.7604,
    "lon": -95.3698
  },
  "Phoenix, US": {
    "lat": 33.4484,
    "lon": -112.074
  },
  "Philadelphia, US": {
    "lat": 39.9526,
    "lon": -75.1652
  },
  "San Antonio, US": {
    "lat": 29.4241,
    "lon": -98.4936
  },
  "San Diego, US": {
    "lat": 32.7157,
    "lon": -117.1619
  },
  "Dallas, US": {
    "lat": 32.7767,
    "lon": -96.797
  },
  "San Jose, US": {
    "lat": 37.3382,
    "lon": -121.8863
  },
  "Austin, US": {
    "lat": 30.2672,
    "lon": -97.7431
  },
  "Jacksonville, US": {
    "lat": 30.3322,
    "lon": -81.6557
  },
  "Fort Worth, US": {
    "lat": 32.7555,
    "lon": -97.3308
  },
  "Columbus, US": {
    "lat": 39.9612,
    "lon": -82.9988
  },
  "Charlotte, US": {
    "lat": 35.2271,
    "lon": -80.8431
  },
  "Indianapolis, US": {
    "lat": 39.7684,
    "lon": -86.1581
  },
  "San Francisco, US": {
    "lat": 37.7749,
    "lon": -122.4194
  },
  "Seattle, US": {
    "lat": 47.6062,
    "lon": -122.3321
  },
  "Denver, US": {
    "lat": 39.7392,
    "lon": -104.9903
  },
  "Washington, US": {
    "lat": 38.9072,
    "lon": -77.0369
  },
  "Boston, US": {
    "lat": 42.3601,
    "lon": -71.0589
  },
  "Nashville, US": {
    "lat": 36.1627,
    "lon": -86.7816
  },
  "Oklahoma City, US": {
    "lat": 35.4676,
    "lon": -97.5164
  },
  "Las Vegas, US": {
    "lat": 36.1699,
    "lon": -115.1398
  },
  "Portland, US": {
    "lat": 45.5152,
    "lon": -122.6784
  },
  "Memphis, US": {
    "lat": 35.1495,
    "lon": -90.049
  },
  "Louisville, US": {
    "lat": 38.2527,
    "lon": -85.7585
  },
  "Baltimore, US": {
    "lat": 39.2904,
    "lon": -76.6122
  },
  "Milwaukee, US": {
    "lat": 43.0389,
    "lon": -87.9065
  },
  "Albuquerque, US": {
    "lat": 35.0844,
    "lon": -106.6504
  },
  "Tucson, US": {
    "lat": 32.2226,
    "lon": -110.9747
  },
  "Fresno, US": {
    "lat": 36.7378,
    "lon": -119.7871
  },
  "Sacramento, US": {
    "lat": 38.5816,
    "lon": -121.4944
  },
  "Mesa, US": {
    "lat": 33.4152,
    "lon": -111.8315
  },
  "Atlanta, US": {
    "lat": 33.749,
    "lon": -84.388
  },
  "Kansas City, US": {
    "lat": 39.0997,
    "lon": -94.5786
  },
  "Colorado Springs, US": {
    "lat": 38.8339,
    "lon": -104.8214
  },
  "Omaha, US": {
    "lat": 41.2565,
    "lon": -95.9345
  },
  "Raleigh, US": {
    "lat": 35.7796,
    "lon": -78.6382
  },
  "Miami, US": {
    "lat": 25.7617,
    "lon": -80.1918
  },
  "Long Beach, US": {
    "lat": 33.7701,
    "lon": -118.1937
  },
  "Virginia Beach, US": {
    "lat": 36.8529,
    "lon": -75.978
  },
  "Oakland, US": {
    "lat": 37.8044,
    "lon": -122.2712
  },
  "Minneapolis, US": {
    "lat": 44.9778,
    "lon": -93.265
  },
  "Tulsa, US": {
    "lat": 36.1539,
    "lon": -95.9928
  },
  "Wichita, US": {
    "lat": 37.6872,
    "lon": -97.3301
  },
  "New Orleans, US": {
    "lat": 29.9511,
    "lon": -90.0715
  },
  "Arlington, US": {
    "lat": 32.7357,
    "lon": -97.1081
  },
  "Cleveland, US": {
    "lat": 41.4993,
    "lon": -81.6944
  },
  "Tampa, US": {
    "lat": 27.9506,
    "lon": -82.4572
  },
  "Anaheim, US": {
    "lat": 33.8366,
    "lon": -117.9143
  },
  "Honolulu, US": {
    "lat": 21.3069,
    "lon": -157.8583
  },
  "Riverside, US": {
    "lat": 33.9806,
    "lon": -117.3755
  },
  "Lexington, US": {
    "lat": 38.0406,
    "lon": -84.5037
  },
  "Stockton, US": {
    "lat": 37.9577,
    "lon": -121.2908
  },
  "Corpus Christi, US": {
    "lat": 27.8006,
    "lon": -97.3964
  },
  "Henderson, US": {
    "lat": 36.0395,
    "lon": -114.9817
  },
  "Saint Paul, US": {
    "lat": 44.9537,
    "lon": -93.09
  },
  "Cincinnati, US": {
    "lat": 39.1031,
    "lon": -84.512
  },
  "Pittsburgh, US": {
    "lat": 40.4406,
    "lon": -79.9959
  },
  "Greensboro, US": {
    "lat": 36.0726,
    "lon": -79.792
  },
  "Anchorage, US": {
    "lat": 61.2181,
    "lon": -149.9003
  },
  "Plano, US": {
    "lat": 33.0198,
    "lon": -96.6989
  },
  "Lincoln, US": {
    "lat": 40.8136,
    "lon": -96.7026
  },
  "Orlando, US": {
    "lat": 28.5383,
    "lon": -81.3792
  },
  "Irvine, US": {
    "lat": 33.6695,
    "lon": -117.8231
  },
  "Newark, US": {
    "lat": 40.7357,
    "lon": -74.1724
  },
  "Toledo, US": {
    "lat": 41.6528,
    "lon": -83.5379
  },
  "Durham, US": {
    "lat": 35.994,
    "lon": -78.8986
  },
  "Chula Vista, US": {
    "lat": 32.6401,
    "lon": -117.0842
  },
  "Fort Wayne, US": {
    "lat": 41.0793,
    "lon": -85.1394
  },
  "Jersey City, US": {
    "lat": 40.7178,
    "lon": -74.0431
  },
  "St. Petersburg, US": {
    "lat": 27.7676,
    "lon": -82.6403
  },
  "Laredo, US": {
    "lat": 27.5036,
    "lon": -99.5076
  },
  "Madison, US": {
    "lat": 43.0731,
    "lon": -89.4012
  },
  "Chandler, US": {
    "lat": 33.3062,
    "lon": -111.8413
  },
  "Buffalo, US": {
    "lat": 42.8864,
    "lon": -78.8784
  },
  "Lubbock, US": {
    "lat": 33.5779,
    "lon": -101.8552
  },
  "Scottsdale, US": {
    "lat": 33.4942,
    "lon": -111.9261
  },
  "Reno, US": {
    "lat": 39.5296,
    "lon": -119.8138
  },
  "Glendale, US": {
    "lat": 34.1425,
    "lon": -118.2551
  },
  "Norfolk, US": {
    "lat": 36.8508,
    "lon": -76.2859
  },
  "Winston–Salem, US": {
    "lat": 36.0999,
    "lon": -80.2442
  },
  "North Las Vegas, US": {
    "lat": 36.1989,
    "lon": -115.1175
  },
  "Gilbert, US": {
    "lat": 33.3528,
    "lon": -111.789
  },
  "Chesapeake, US": {
    "lat": 36.7682,
    "lon": -76.2875
  },
  "Irving, US": {
    "lat": 32.814,
    "lon": -96.9489
  },
  "Garland, US": {
    "lat": 32.9126,
    "lon": -96.6389
  },
  "Fremont, US": {
    "lat": 37.5485,
    "lon": -121.9886
  },
  "Baton Rouge, US": {
    "lat": 30.4515,
    "lon": -91.1871
  },
  "Richmond, US": {
    "lat": 37.9358,
    "lon": -122.3477
  },
  "Boise, US": {
    "lat": 43.615,
    "lon": -116.2023
  },
  "Spokane, US": {
    "lat": 47.6588,
    "lon": -117.426
  },
  "Des Moines, US": {
    "lat": 41.5868,
    "lon": -93.625
  },
  "Tacoma, US": {
    "lat": 47.2529,
    "lon": -122.4443
  },
  "San Bernardino, US": {
    "lat": 34.1083,
    "lon": -117.2898
  },
  "Modesto, US": {
    "lat": 37.6391,
    "lon": -120.9969
  },
  "Fontana, US": {
    "lat": 34.0922,
    "lon": -117.4351
  },
  "Oxnard, US": {
    "lat": 34.1975,
    "lon": -119.1771
  },
  "Moreno Valley, US": {
    "lat": 33.9425,
    "lon": -117.2297
  },
  "Fayetteville, US": {
    "lat": 35.0527,
    "lon": -78.8784
  },
  "Huntington Beach, US": {
    "lat": 33.6603,
    "lon": -117.9992
  },
  "Yonkers, US": {
    "lat": 40.9312,
    "lon": -73.8987
  },
  "Aurora, US": {
    "lat": 39.7294,
    "lon": -104.8319
  },
  "Montreal, CA": {
    "lat": 45.5017,
    "lon": -73.5673
  },
  "Vancouver, CA": {
    "lat": 49.2827,
    "lon": -123.1207
  },
  "Calgary, CA": {
    "lat": 51.0486,
    "lon": -114.0708
  },
  "Edmonton, CA": {
    "lat": 53.5444,
    "lon": -113.4909
  },
  "Ottawa, CA": {
    "lat": 45.4215,
    "lon": -75.6972
  },
  "Winnipeg, CA": {
    "lat": 49.8951,
    "lon": -97.1384
  },
  "Quebec City, CA": {
    "lat": 46.8139,
    "lon": -71.208
  },
  "Hamilton, CA": {
    "lat": 43.2557,
    "lon": -79.8711
  },
  "Kitchener, CA": {
    "lat": 43.4516,
    "lon": -80.4928
  },
  "London, CA": {
    "lat": 42.9849,
    "lon": -81.2453
  },
  "Victoria, CA": {
    "lat": 48.4284,
    "lon": -123.3656
  },
  "Halifax, CA": {
    "lat": 44.6488,
    "lon": -63.5752
  },
  "Oshawa, CA": {
    "lat": 43.8971,
    "lon": -78.8635
  },
  "Windsor, CA": {
    "lat": 42.3149,
    "lon": -83.0364
  },
  "Saskatoon, CA": {
    "lat": 52.1332,
    "lon": -106.67
  },
  "Regina, CA": {
    "lat": 50.4452,
    "lon": -104.6189
  },
  "Barrie, CA": {
    "lat": 44.3894,
    "lon": -79.6903
  },
  "St. Catharines, CA": {
    "lat": 43.1594,
    "lon": -79.2469
  },
  "Sherbrooke, CA": {
    "lat": 45.4001,
    "lon": -71.8824
  },
  "São Paulo, BR": {
    "lat": -23.5505,
    "lon": -46.6333
  },
  "Rio de Janeiro, BR": {
    "lat": -22.9068,
    "lon": -43.1729
  },
  "Brasília, BR": {
    "lat": -15.7942,
    "lon": -47.8825
  },
  "Salvador, BR": {
    "lat": -12.9714,
    "lon": -38.5014
  },
  "Fortaleza, BR": {
    "lat": -3.7172,
    "lon": -38.5434
  },
  "Belo Horizonte, BR": {
    "lat": -19.9167,
    "lon": -43.9345
  },
  "Manaus, BR": {
    "lat": -3.119,
    "lon": -60.0217
  },
  "Curitiba, BR": {
    "lat": -25.4296,
    "lon": -49.2671
  },
  "Recife, BR": {
    "lat": -8.0476,
    "lon": -34.877
  },
  "Porto Alegre, BR": {
    "lat": -30.0346,
    "lon": -51.2177
  },
  "Goiânia, BR": {
    "lat": -16.6869,
    "lon": -49.2643
  },
  "Belém, BR": {
    "lat": -1.4558,
    "lon": -48.4902
  },
  "Guarulhos, BR": {
    "lat": -23.454,
    "lon": -46.5333
  },
  "Campinas, BR": {
    "lat": -22.9099,
    "lon": -47.0626
  },
  "São Luís, BR": {
    "lat": -2.5391,
    "lon": -44.2825
  },
  "Maceió, BR": {
    "lat": -9.6498,
    "lon": -35.7089
  },
  "Duque de Caxias, BR": {
    "lat": -22.7856,
    "lon": -43.3117
  },
  "Natal, BR": {
    "lat": -5.7945,
    "lon": -35.211
  },
  "Teresina, BR": {
    "lat": -5.0918,
    "lon": -42.8034
  },
  "Campo Grande, BR": {
    "lat": -20.4428,
    "lon": -54.6464
  },
  "São Bernardo do Campo, BR": {
    "lat": -23.6939,
    "lon": -46.565
  },
  "João Pessoa, BR": {
    "lat": -7.115,
    "lon": -34.8631
  },
  "Nova Iguaçu, BR": {
    "lat": -22.7592,
    "lon": -43.4511
  },
  "Santo André, BR": {
    "lat": -23.6645,
    "lon": -46.5314
  },
  "Osasco, BR": {
    "lat": -23.5325,
    "lon": -46.7917
  },
  "São José dos Campos, BR": {
    "lat": -23.1794,
    "lon": -45.8872
  },
  "Jundiaí, BR": {
    "lat": -23.1857,
    "lon": -46.884
  },
  "Ribeirão Preto, BR": {
    "lat": -21.1704,
    "lon": -47.8103
  },
  "Sorocaba, BR": {
    "lat": -23.5015,
    "lon": -47.4581
  },
  "Uberlândia, BR": {
    "lat": -18.9113,
    "lon": -48.2622
  },
  "Aracaju, BR": {
    "lat": -10.9472,
    "lon": -37.0731
  },
  "Feira de Santana, BR": {
    "lat": -12.2664,
    "lon": -38.9649
  },
  "Cuiabá, BR": {
    "lat": -15.601,
    "lon": -56.0979
  },
  "Joinville, BR": {
    "lat": -26.3045,
    "lon": -48.8487
  },
  "Aparecida de Goiânia, BR": {
    "lat": -16.8198,
    "lon": -49.245
  },
  "Londrina, BR": {
    "lat": -23.3045,
    "lon": -51.1696
  },
  "Niterói, BR": {
    "lat": -22.8833,
    "lon": -43.1034
  },
  "Ananindeua, BR": {
    "lat": -1.3639,
    "lon": -48.3719
  },
  "Porto Velho, BR": {
    "lat": -8.7619,
    "lon": -63.9039
  },
  "Serra, BR": {
    "lat": -20.1289,
    "lon": -40.3078
  },
  "Caxias do Sul, BR": {
    "lat": -29.1681,
    "lon": -51.1794
  },
  "Macapá, BR": {
    "lat": 0.0356,
    "lon": -51.0705
  },
  "Campos dos Goytacazes, BR": {
    "lat": -21.7545,
    "lon": -41.3246
  },
  "Florianópolis, BR": {
    "lat": -27.5949,
    "lon": -48.5482
  },
  "Vila Velha, BR": {
    "lat": -20.3417,
    "lon": -40.2925
  },
  "Mauá, BR": {
    "lat": -23.6686,
    "lon": -46.4608
  },
  "São João de Meriti, BR": {
    "lat": -22.8039,
    "lon": -43.3722
  },
  "Olinda, BR": {
    "lat": -8.0089,
    "lon": -34.8553
  },
  "Carapicuíba, BR": {
    "lat": -23.5235,
    "lon": -46.8406
  },
  "Contagem, BR": {
    "lat": -19.9167,
    "lon": -44.0833
  },
  "Juiz de Fora, BR": {
    "lat": -21.7622,
    "lon": -43.3503
  },
  "Piracicaba, BR": {
    "lat": -22.7253,
    "lon": -47.6492
  },
  "Franca, BR": {
    "lat": -20.5386,
    "lon": -47.4008
  },
  "Petrópolis, BR": {
    "lat": -22.505,
    "lon": -43.1786
  },
  "Canoas, BR": {
    "lat": -29.9178,
    "lon": -51.1836
  },
  "Bauru, BR": {
    "lat": -22.3147,
    "lon": -49.0606
  },
  "Pelotas, BR": {
    "lat": -31.7719,
    "lon": -52.3425
  },
  "Vitória da Conquista, BR": {
    "lat": -14.861,
    "lon": -40.8398
  },
  "Blumenau, BR": {
    "lat": -26.9194,
    "lon": -49.0661
  },
  "Ponta Grossa, BR": {
    "lat": -25.095,
    "lon": -50.1619
  },
  "Santarém, BR": {
    "lat": -2.4431,
    "lon": -54.7083
  },
  "Mexico City, MX": {
    "lat": 19.4326,
    "lon": -99.1332
  },
  "Guadalajara, MX": {
    "lat": 20.6597,
    "lon": -103.3496
  },
  "Monterrey, MX": {
    "lat": 25.6866,
    "lon": -100.3161
  },
  "Puebla, MX": {
    "lat": 19.0414,
    "lon": -98.2063
  },
  "Tijuana, MX": {
    "lat": 32.5149,
    "lon": -117.0382
  },
  "León, MX": {
    "lat": 21.125,
    "lon": -101.6856
  },
  "Juárez, MX": {
    "lat": 31.6904,
    "lon": -106.4245
  },
  "Zapopan, MX": {
    "lat": 20.7236,
    "lon": -103.3848
  },
  "Nezahualcóyotl, MX": {
    "lat": 19.4006,
    "lon": -99.0149
  },
  "Mexicali, MX": {
    "lat": 32.6245,
    "lon": -115.4522
  },
  "Culiacán, MX": {
    "lat": 24.8042,
    "lon": -107.4311
  },
  "Querétaro, MX": {
    "lat": 20.5881,
    "lon": -100.3899
  },
  "Chihuahua, MX": {
    "lat": 28.633,
    "lon": -106.0691
  },
  "Mérida, MX": {
    "lat": 20.9674,
    "lon": -89.5926
  },
  "Saltillo, MX": {
    "lat": 25.4232,
    "lon": -101.0053
  },
  "Aguascalientes, MX": {
    "lat": 21.8853,
    "lon": -102.2916
  },
  "Hermosillo, MX": {
    "lat": 29.0729,
    "lon": -110.9559
  },
  "Morelia, MX": {
    "lat": 19.7008,
    "lon": -101.1844
  },
  "Cancún, MX": {
    "lat": 21.1743,
    "lon": -86.8466
  },
  "San Luis Potosí, MX": {
    "lat": 22.1565,
    "lon": -100.9855
  },
  "Torreón, MX": {
    "lat": 25.5393,
    "lon": -103.4068
  },
  "Tlalnepantla de Baz, MX": {
    "lat": 19.5369,
    "lon": -99.1949
  },
  "Acapulco, MX": {
    "lat": 16.8531,
    "lon": -99.8237
  },
  "Tuxtla Gutiérrez, MX": {
    "lat": 16.7516,
    "lon": -93.1167
  },
  "Reynosa, MX": {
    "lat": 26.0806,
    "lon": -98.2884
  },
  "Tlaquepaque, MX": {
    "lat": 20.6167,
    "lon": -103.3167
  },
  "Guadalupe, MX": {
    "lat": 25.677,
    "lon": -100.2597
  },
  "Victoria de Durango, MX": {
    "lat": 24.0277,
    "lon": -104.6532
  },
  "Matamoros, MX": {
    "lat": 25.869,
    "lon": -97.5028
  },
  "Ecatepec de Morelos, MX": {
    "lat": 19.5999,
    "lon": -99.0512
  },
  "Veracruz, MX": {
    "lat": 19.1738,
    "lon": -96.1342
  },
  "Buenos Aires, AR": {
    "lat": -34.6037,
    "lon": -58.3816
  },
  "Córdoba, AR": {
    "lat": -31.4135,
    "lon": -64.1811
  },
  "Rosario, AR": {
    "lat": -32.9468,
    "lon": -60.636
  },
  "La Plata, AR": {
    "lat": -34.9215,
    "lon": -57.9545
  },
  "Mar del Plata, AR": {
    "lat": -38.0023,
    "lon": -57.5575
  },
  "San Miguel de Tucumán, AR": {
    "lat": -26.8083,
    "lon": -65.2176
  },
  "Salta, AR": {
    "lat": -24.7859,
    "lon": -65.4117
  },
  "Santa Fe, AR": {
    "lat": -31.6107,
    "lon": -60.6973
  },
  "Corrientes, AR": {
    "lat": -27.4806,
    "lon": -58.8341
  },
  "Bahía Blanca, AR": {
    "lat": -38.7196,
    "lon": -62.2724
  },
  "Resistencia, AR": {
    "lat": -27.4506,
    "lon": -58.9839
  },
  "Posadas, AR": {
    "lat": -27.3671,
    "lon": -55.8961
  },
  "Santiago del Estero, AR": {
    "lat": -27.7951,
    "lon": -64.2615
  },
  "Neuquén, AR": {
    "lat": -38.9516,
    "lon": -68.0591
  },
  "Paraná, AR": {
    "lat": -31.7413,
    "lon": -60.5115
  },
  "Bogotá, CO": {
    "lat": 4.711,
    "lon": -74.0721
  },
  "Medellín, CO": {
    "lat": 6.2442,
    "lon": -75.5812
  },
  "Cali, CO": {
    "lat": 3.4372,
    "lon": -76.5225
  },
  "Barranquilla, CO": {
    "lat": 10.9685,
    "lon": -74.7813
  },
  "Cartagena, CO": {
    "lat": 10.391,
    "lon": -75.4794
  },
  "Cúcuta, CO": {
    "lat": 7.8939,
    "lon": -72.5078
  },
  "Bucaramanga, CO": {
    "lat": 7.1254,
    "lon": -73.1198
  },
  "Pereira, CO": {
    "lat": 4.8133,
    "lon": -75.6946
  },
  "Santa Marta, CO": {
    "lat": 11.2408,
    "lon": -74.199
  },
  "Ibagué, CO": {
    "lat": 4.4389,
    "lon": -75.2322
  },
  "Pasto, CO": {
    "lat": 1.2136,
    "lon": -77.2811
  },
  "Manizales, CO": {
    "lat": 5.0689,
    "lon": -75.5174
  },
  "Neiva, CO": {
    "lat": 2.9273,
    "lon": -75.2819
  },
  "Villavicencio, CO": {
    "lat": 4.142,
    "lon": -73.6266
  },
  "Armenia, CO": {
    "lat": 4.5339,
    "lon": -75.6811
  },
  "Valledupar, CO": {
    "lat": 10.4631,
    "lon": -73.2532
  },
  "Montería, CO": {
    "lat": 8.7479,
    "lon": -75.8814
  },
  "Quito, EC": {
    "lat": -0.1807,
    "lon": -78.4678
  },
  "Guayaquil, EC": {
    "lat": -2.1894,
    "lon": -79.8891
  },
  "Cuenca, EC": {
    "lat": -2.9001,
    "lon": -79.0059
  },
  "Santo Domingo de los Tsáchilas, EC": {
    "lat": -0.2542,
    "lon": -79.1719
  },
  "Machala, EC": {
    "lat": -3.2586,
    "lon": -79.9554
  },
  "Durán, EC": {
    "lat": -2.1667,
    "lon": -79.8333
  },
  "Manta, EC": {
    "lat": -0.9677,
    "lon": -80.7089
  },
  "Portoviejo, EC": {
    "lat": -1.0546,
    "lon": -80.4505
  },
  "Ambato, EC": {
    "lat": -1.2491,
    "lon": -78.6167
  },
  "Riobamba, EC": {
    "lat": -1.671,
    "lon": -78.6477
  },
  "Lima, PE": {
    "lat": -12.0464,
    "lon": -77.0428
  },
  "Arequipa, PE": {
    "lat": -16.3989,
    "lon": -71.535
  },
  "Trujillo, PE": {
    "lat": -8.109,
    "lon": -79.0215
  },
  "Chiclayo, PE": {
    "lat": -6.7712,
    "lon": -79.8409
  },
  "Iquitos, PE": {
    "lat": -3.7437,
    "lon": -73.2516
  },
  "Piura, PE": {
    "lat": -5.1945,
    "lon": -80.6328
  },
  "Cusco, PE": {
    "lat": -13.5319,
    "lon": -71.9675
  },
  "Huancayo, PE": {
    "lat": -12.0686,
    "lon": -75.2102
  },
  "Tacna, PE": {
    "lat": -18.0147,
    "lon": -70.2536
  },
  "Juliaca, PE": {
    "lat": -15.5,
    "lon": -70.1333
  },
  "Santiago, CL": {
    "lat": -33.4489,
    "lon": -70.6693
  },
  "Valparaíso, CL": {
    "lat": -33.0472,
    "lon": -71.6127
  },
  "Concepción, CL": {
    "lat": -36.827,
    "lon": -73.0504
  },
  "Viña del Mar, CL": {
    "lat": -33.0246,
    "lon": -71.5518
  },
  "Antofagasta, CL": {
    "lat": -23.6524,
    "lon": -70.3954
  },
  "Temuco, CL": {
    "lat": -38.7359,
    "lon": -72.59
  },
  "Rancagua, CL": {
    "lat": -34.1708,
    "lon": -70.7444
  },
  "Talca, CL": {
    "lat": -35.4264,
    "lon": -71.6554
  },
  "Caracas, VE": {
    "lat": 10.488,
    "lon": -66.8792
  },
  "Maracaibo, VE": {
    "lat": 10.6545,
    "lon": -71.7145
  },
  "Valencia, VE": {
    "lat": 10.162,
    "lon": -68.0077
  },
  "Barquisimeto, VE": {
    "lat": 10.0678,
    "lon": -69.3474
  },
  "Ciudad Guayana, VE": {
    "lat": 8.3447,
    "lon": -62.6694
  },
  "Maturín, VE": {
    "lat": 9.7457,
    "lon": -63.1767
  },
  "Barcelona, VE": {
    "lat": 10.1454,
    "lon": -64.6862
  },
  "Maracay, VE": {
    "lat": 10.2469,
    "lon": -67.5967
  },
  "Gothenburg, SE": {
    "lat": 57.7089,
    "lon": 11.9746
  },
  "Malmö, SE": {
    "lat": 55.605,
    "lon": 13.0038
  },
  "Uppsala, SE": {
    "lat": 59.8586,
    "lon": 17.6389
  },
  "Västerås, SE": {
    "lat": 59.6099,
    "lon": 16.5448
  },
  "Örebro, SE": {
    "lat": 59.2741,
    "lon": 15.2066
  },
  "Linköping, SE": {
    "lat": 58.4108,
    "lon": 15.6216
  },
  "Helsingborg, SE": {
    "lat": 56.0465,
    "lon": 12.6944
  },
  "Jönköping, SE": {
    "lat": 57.7815,
    "lon": 14.1562
  },
  "Norrköping, SE": {
    "lat": 58.5942,
    "lon": 16.1826
  },
  "Lund, SE": {
    "lat": 55.7058,
    "lon": 13.1932
  },
  "Umeå, SE": {
    "lat": 63.8284,
    "lon": 20.2597
  },
  "Gävle, SE": {
    "lat": 60.6749,
    "lon": 17.1417
  },
  "Borås, SE": {
    "lat": 57.721,
    "lon": 12.9401
  },
  "Bergen, NO": {
    "lat": 60.3928,
    "lon": 5.3242
  },
  "Trondheim, NO": {
    "lat": 63.4305,
    "lon": 10.3951
  },
  "Stavanger, NO": {
    "lat": 58.97,
    "lon": 5.7331
  },
  "Drammen, NO": {
    "lat": 59.7378,
    "lon": 10.2046
  },
  "Fredrikstad, NO": {
    "lat": 59.2181,
    "lon": 10.9298
  },
  "Kristiansand, NO": {
    "lat": 58.1467,
    "lon": 7.9956
  },
  "Aalborg, DK": {
    "lat": 57.048,
    "lon": 9.9217
  },
  "Aarhus, DK": {
    "lat": 56.1567,
    "lon": 10.2108
  },
  "Odense, DK": {
    "lat": 55.4038,
    "lon": 10.4024
  },
  "Esbjerg, DK": {
    "lat": 55.4765,
    "lon": 8.4596
  },
  "Randers, DK": {
    "lat": 56.4607,
    "lon": 10.0364
  },
  "Kolding, DK": {
    "lat": 55.4904,
    "lon": 9.4722
  },
  "Vejle, DK": {
    "lat": 55.7093,
    "lon": 9.5357
  },
  "Horsens, DK": {
    "lat": 55.8607,
    "lon": 9.8503
  },
  "Roskilde, DK": {
    "lat": 55.6415,
    "lon": 12.0803
  },
  "Herning, DK": {
    "lat": 56.1362,
    "lon": 8.9766
  },
  "Silkeborg, DK": {
    "lat": 56.1697,
    "lon": 9.5451
  },
  "Næstved, DK": {
    "lat": 55.2299,
    "lon": 11.7609
  },
  "Fredericia, DK": {
    "lat": 55.5657,
    "lon": 9.7526
  },
  "Viborg, DK": {
    "lat": 56.4506,
    "lon": 9.402
  },
  "Køge, DK": {
    "lat": 55.458,
    "lon": 12.1821
  },
  "Holstebro, DK": {
    "lat": 56.36,
    "lon": 8.6161
  },
  "Taastrup, DK": {
    "lat": 55.6501,
    "lon": 12.2923
  },
  "Slagelse, DK": {
    "lat": 55.4028,
    "lon": 11.3546
  },
  "Hillerød, DK": {
    "lat": 55.9279,
    "lon": 12.3008
  },
  "Antwerpen, BE": {
    "lat": 51.2199,
    "lon": 4.4025
  },
  "Leuven, BE": {
    "lat": 50.8798,
    "lon": 4.7009
  },
  "Gent, BE": {
    "lat": 51.0543,
    "lon": 3.7174
  },
  "Charleroi, BE": {
    "lat": 50.4114,
    "lon": 4.4445
  },
  "Liège, BE": {
    "lat": 50.6337,
    "lon": 5.5675
  },
  "Namur, BE": {
    "lat": 50.4669,
    "lon": 4.8675
  },
  "Mechelen, BE": {
    "lat": 51.0257,
    "lon": 4.4776
  },
  "Genk, BE": {
    "lat": 50.9667,
    "lon": 5.5
  },
  "Kortrijk, BE": {
    "lat": 50.828,
    "lon": 3.2649
  },
  "Ostend, BE": {
    "lat": 51.2253,
    "lon": 2.9118
  },
  "Aachen, DE": {
    "lat": 50.7753,
    "lon": 6.0839
  },
  "Augsburg, DE": {
    "lat": 48.3705,
    "lon": 10.8978
  },
  "Bielefeld, DE": {
    "lat": 52.0302,
    "lon": 8.5325
  },
  "Bochum, DE": {
    "lat": 51.4818,
    "lon": 7.2165
  },
  "Bonn, DE": {
    "lat": 50.7374,
    "lon": 7.0982
  },
  "Bremen, DE": {
    "lat": 53.0793,
    "lon": 8.8017
  },
  "Dresden, DE": {
    "lat": 51.0504,
    "lon": 13.7373
  },
  "Düsseldorf, DE": {
    "lat": 51.2277,
    "lon": 6.7735
  },
  "Essen, DE": {
    "lat": 51.4556,
    "lon": 7.0116
  },
  "Hanover, DE": {
    "lat": 52.3759,
    "lon": 9.732
  },
  "Karlsruhe, DE": {
    "lat": 49.0069,
    "lon": 8.4037
  },
  "Leipzig, DE": {
    "lat": 51.3397,
    "lon": 12.3714
  },
  "Mönchengladbach, DE": {
    "lat": 51.1809,
    "lon": 6.4424
  },
  "Nuremberg, DE": {
    "lat": 49.4521,
    "lon": 11.0767
  },
  "Stuttgart, DE": {
    "lat": 48.7758,
    "lon": 9.1829
  },
  "Wuppertal, DE": {
    "lat": 51.2563,
    "lon": 7.1508
  },
  "Mannheim, DE": {
    "lat": 49.4875,
    "lon": 8.466
  },
  "Kiel, DE": {
    "lat": 54.3233,
    "lon": 10.1228
  },
  "Wiesbaden, DE": {
    "lat": 50.0782,
    "lon": 8.2398
  },
  "Münster, DE": {
    "lat": 51.9607,
    "lon": 7.6261
  },
  "Gelsenkirchen, DE": {
    "lat": 51.5177,
    "lon": 7.0857
  },
  "Braunschweig, DE": {
    "lat": 52.2689,
    "lon": 10.5268
  },
  "Chemnitz, DE": {
    "lat": 50.8357,
    "lon": 12.9292
  },
  "Halle (Saale), DE": {
    "lat": 51.4816,
    "lon": 11.9795
  },
  "Magdeburg, DE": {
    "lat": 52.1205,
    "lon": 11.6276
  },
  "Freiburg im Breisgau, DE": {
    "lat": 47.999,
    "lon": 7.8421
  },
  "Krefeld, DE": {
    "lat": 51.3388,
    "lon": 6.5625
  },
  "Lübeck, DE": {
    "lat": 53.8659,
    "lon": 10.6873
  },
  "Oberhausen, DE": {
    "lat": 51.4781,
    "lon": 6.8807
  },
  "Erfurt, DE": {
    "lat": 50.9848,
    "lon": 11.0299
  },
  "Kassel, DE": {
    "lat": 51.3127,
    "lon": 9.4797
  },
  "Hagen, DE": {
    "lat": 51.3608,
    "lon": 7.4717
  },
  "Saarbrücken, DE": {
    "lat": 49.2326,
    "lon": 7.0098
  },
  "Hamm, DE": {
    "lat": 51.6803,
    "lon": 7.8151
  },
  "Potsdam, DE": {
    "lat": 52.3906,
    "lon": 13.0647
  },
  "Oldenburg, DE": {
    "lat": 53.1412,
    "lon": 8.2147
  },
  "Leverkusen, DE": {
    "lat": 51.0333,
    "lon": 7
  },
  "Solingen, DE": {
    "lat": 51.1653,
    "lon": 7.0676
  },
  "Osnabrück, DE": {
    "lat": 52.2726,
    "lon": 8.0498
  },
  "Heidelberg, DE": {
    "lat": 49.3988,
    "lon": 8.6724
  },
  "Darmstadt, DE": {
    "lat": 49.8728,
    "lon": 8.6512
  },
  "Regensburg, DE": {
    "lat": 49.0134,
    "lon": 12.1016
  },
  "Ingolstadt, DE": {
    "lat": 48.7665,
    "lon": 11.425
  },
  "Würzburg, DE": {
    "lat": 49.7913,
    "lon": 9.9534
  },
  "Wolfsburg, DE": {
    "lat": 52.4227,
    "lon": 10.7864
  },
  "Göttingen, DE": {
    "lat": 51.5413,
    "lon": 9.9158
  },
  "Offenbach am Main, DE": {
    "lat": 50.1006,
    "lon": 8.7665
  },
  "Ulm, DE": {
    "lat": 48.3984,
    "lon": 9.9916
  },
  "Paderborn, DE": {
    "lat": 51.7191,
    "lon": 8.7544
  },
  "Heilbronn, DE": {
    "lat": 49.1427,
    "lon": 9.2109
  },
  "Salzburg, AT": {
    "lat": 47.8095,
    "lon": 13.055
  },
  "Innsbruck, AT": {
    "lat": 47.2692,
    "lon": 11.4041
  },
  "Graz, AT": {
    "lat": 47.0667,
    "lon": 15.45
  },
  "Linz, AT": {
    "lat": 48.3069,
    "lon": 14.2858
  },
  "Klagenfurt, AT": {
    "lat": 46.6365,
    "lon": 14.3122
  },
  "Bregenz, AT": {
    "lat": 47.5031,
    "lon": 9.7471
  },
  "St. Pölten, AT": {
    "lat": 48.2035,
    "lon": 15.6269
  },
  "Eindhoven, NL": {
    "lat": 51.4416,
    "lon": 5.4697
  },
  "Tilburg, NL": {
    "lat": 51.5719,
    "lon": 5.0828
  },
  "Groningen, NL": {
    "lat": 53.2194,
    "lon": 6.5665
  },
  "Breda, NL": {
    "lat": 51.5866,
    "lon": 4.776
  },
  "Nijmegen, NL": {
    "lat": 51.8425,
    "lon": 5.8528
  },
  "Apeldoorn, NL": {
    "lat": 52.211,
    "lon": 5.9699
  },
  "Haarlem, NL": {
    "lat": 52.3874,
    "lon": 4.6462
  },
  "Arnhem, NL": {
    "lat": 51.9795,
    "lon": 5.9111
  },
  "Zaanstad, NL": {
    "lat": 52.4531,
    "lon": 4.8136
  },
  "’s-Hertogenbosch, NL": {
    "lat": 51.6992,
    "lon": 5.3042
  },
  "Zwolle, NL": {
    "lat": 52.5167,
    "lon": 6.0833
  },
  "Maastricht, NL": {
    "lat": 50.8483,
    "lon": 5.6889
  },
  "Leiden, NL": {
    "lat": 52.1601,
    "lon": 4.493
  },
  "Dordrecht, NL": {
    "lat": 51.81,
    "lon": 4.6697
  },
  "Almere, NL": {
    "lat": 52.3671,
    "lon": 5.2168
  },
  "Strasbourg, FR": {
    "lat": 48.5734,
    "lon": 7.7521
  },
  "Nantes, FR": {
    "lat": 47.2184,
    "lon": -1.5536
  },
  "Montpellier, FR": {
    "lat": 43.6108,
    "lon": 3.8767
  },
  "Rennes, FR": {
    "lat": 48.1113,
    "lon": -1.6743
  },
  "Grenoble, FR": {
    "lat": 45.1885,
    "lon": 5.7245
  },
  "Rouen, FR": {
    "lat": 49.4432,
    "lon": 1.0995
  },
  "Toulon, FR": {
    "lat": 43.1242,
    "lon": 5.9284
  },
  "Angers, FR": {
    "lat": 47.4716,
    "lon": -0.5518
  },
  "Dijon, FR": {
    "lat": 47.322,
    "lon": 5.0415
  },
  "Nîmes, FR": {
    "lat": 43.8367,
    "lon": 4.3601
  },
  "Saint-Étienne, FR": {
    "lat": 45.4397,
    "lon": 4.3872
  },
  "Le Havre, FR": {
    "lat": 49.4944,
    "lon": 0.1079
  },
  "Reims, FR": {
    "lat": 49.2583,
    "lon": 4.0317
  },
  "Brest, FR": {
    "lat": 48.3904,
    "lon": -4.4861
  },
  "Zaragoza, ES": {
    "lat": 41.6488,
    "lon": -0.8891
  },
  "Málaga, ES": {
    "lat": 36.7213,
    "lon": -4.4213
  },
  "Murcia, ES": {
    "lat": 37.9922,
    "lon": -1.1307
  },
  "Palma, ES": {
    "lat": 39.5696,
    "lon": 2.6502
  },
  "Las Palmas de Gran Canaria, ES": {
    "lat": 28.1235,
    "lon": -15.4363
  },
  "Alicante, ES": {
    "lat": 38.3452,
    "lon": -0.4815
  },
  "Córdoba, ES": {
    "lat": 37.8916,
    "lon": -4.7728
  },
  "Valladolid, ES": {
    "lat": 41.6523,
    "lon": -4.7245
  },
  "Vigo, ES": {
    "lat": 42.2367,
    "lon": -8.7246
  },
  "Gijón, ES": {
    "lat": 43.5357,
    "lon": -5.6615
  },
  "L'Hospitalet de Llobregat, ES": {
    "lat": 41.3597,
    "lon": 2.1003
  },
  "Vitoria-Gasteiz, ES": {
    "lat": 42.8467,
    "lon": -2.6724
  },
  "A Coruña, ES": {
    "lat": 43.3623,
    "lon": -8.4115
  },
  "Oviedo, ES": {
    "lat": 43.3619,
    "lon": -5.8494
  },
  "Cartagena, ES": {
    "lat": 37.6057,
    "lon": -0.9862
  },
  "Terrassa, ES": {
    "lat": 41.5632,
    "lon": 2.0089
  },
  "Jerez de la Frontera, ES": {
    "lat": 36.6864,
    "lon": -6.1361
  },
  "Sabadell, ES": {
    "lat": 41.5485,
    "lon": 2.1073
  },
  "Pamplona, ES": {
    "lat": 42.8125,
    "lon": -1.6458
  },
  "Almería, ES": {
    "lat": 36.834,
    "lon": -2.4645
  },
  "Léon, ES": {
    "lat": 42.5987,
    "lon": -5.5703
  },
  "Castellón de la Plana, ES": {
    "lat": 39.9864,
    "lon": -0.0513
  },
  "Burgos, ES": {
    "lat": 42.3411,
    "lon": -3.7045
  },
  "Santander, ES": {
    "lat": 43.4623,
    "lon": -3.8098
  },
  "Salamanca, ES": {
    "lat": 40.9688,
    "lon": -5.6639
  },
  "Logroño, ES": {
    "lat": 42.4627,
    "lon": -2.4449
  },
  "Badajoz, ES": {
    "lat": 38.8794,
    "lon": -6.9707
  },
  "Huelva, ES": {
    "lat": 37.2583,
    "lon": -6.9508
  },
  "Tarragona, ES": {
    "lat": 41.1189,
    "lon": 1.2496
  },
  "Lleida, ES": {
    "lat": 41.6176,
    "lon": 0.6222
  },
  "Marbella, ES": {
    "lat": 36.5099,
    "lon": -4.8824
  },
  "Cadiz, ES": {
    "lat": 36.5271,
    "lon": -6.2886
  },
  "Kraków, PL": {
    "lat": 50.0647,
    "lon": 19.945
  },
  "Łódź, PL": {
    "lat": 51.7592,
    "lon": 19.456
  },
  "Wrocław, PL": {
    "lat": 51.1079,
    "lon": 17.0385
  },
  "Poznań, PL": {
    "lat": 52.4064,
    "lon": 16.9252
  },
  "Gdańsk, PL": {
    "lat": 54.352,
    "lon": 18.6466
  },
  "Bydgoszcz, PL": {
    "lat": 53.1235,
    "lon": 18.0084
  },
  "Lublin, PL": {
    "lat": 51.2465,
    "lon": 22.5684
  },
  "Katowice, PL": {
    "lat": 50.2649,
    "lon": 19.0238
  },
  "Białystok, PL": {
    "lat": 53.1325,
    "lon": 23.1688
  },
  "Gdynia, PL": {
    "lat": 54.5189,
    "lon": 18.5305
  },
  "Częstochowa, PL": {
    "lat": 50.8118,
    "lon": 19.1203
  },
  "Radom, PL": {
    "lat": 51.4025,
    "lon": 21.1471
  },
  "Sosnowiec, PL": {
    "lat": 50.2868,
    "lon": 19.1039
  },
  "Toruń, PL": {
    "lat": 53.0138,
    "lon": 18.5984
  },
  "Kielce, PL": {
    "lat": 50.8703,
    "lon": 20.6275
  },
  "Gliwice, PL": {
    "lat": 50.2945,
    "lon": 18.6714
  },
  "Zabrze, PL": {
    "lat": 50.3249,
    "lon": 18.7858
  },
  "Bytom, PL": {
    "lat": 50.348,
    "lon": 18.9328
  },
  "Bielsko-Biała, PL": {
    "lat": 49.8225,
    "lon": 19.0444
  },
  "Olsztyn, PL": {
    "lat": 53.7761,
    "lon": 20.4798
  },
  "Rzeszów, PL": {
    "lat": 50.0412,
    "lon": 21.999
  },
  "Ruda Śląska, PL": {
    "lat": 50.2584,
    "lon": 18.8536
  },
  "Rybnik, PL": {
    "lat": 50.1021,
    "lon": 18.5464
  },
  "Tychy, PL": {
    "lat": 50.1236,
    "lon": 18.9664
  },
  "Dąbrowa Górnicza, PL": {
    "lat": 50.333,
    "lon": 19.2
  },
  "Płock, PL": {
    "lat": 52.5468,
    "lon": 19.7064
  },
  "Opole, PL": {
    "lat": 50.6751,
    "lon": 17.921
  },
  "Elbląg, PL": {
    "lat": 54.1522,
    "lon": 19.4086
  },
  "Wałbrzych, PL": {
    "lat": 50.7714,
    "lon": 16.2843
  },
  "Włocławek, PL": {
    "lat": 52.6482,
    "lon": 19.0677
  },
  "Tarnów, PL": {
    "lat": 50.0121,
    "lon": 20.9858
  },
  "Chorzów, PL": {
    "lat": 50.3058,
    "lon": 18.9742
  },
  "Koszalin, PL": {
    "lat": 54.1944,
    "lon": 16.1722
  },
  "Kalisz, PL": {
    "lat": 51.7611,
    "lon": 18.091
  },
  "Legnica, PL": {
    "lat": 51.2079,
    "lon": 16.1619
  },
  "Grudziądz, PL": {
    "lat": 53.4841,
    "lon": 18.7537
  },
  "Slupsk, PL": {
    "lat": 54.4641,
    "lon": 17.0283
  },
  "Jaworzno, PL": {
    "lat": 50.2026,
    "lon": 19.2739
  },
  "Jastrzębie-Zdrój, PL": {
    "lat": 50.1817,
    "lon": 18.5986
  },
  "Prato, IT": {
    "lat": 43.8806,
    "lon": 11.0966
  },
  "Palermo, IT": {
    "lat": 38.1157,
    "lon": 13.3615
  },
  "Genoa, IT": {
    "lat": 44.4056,
    "lon": 8.9463
  },
  "Bologna, IT": {
    "lat": 44.4949,
    "lon": 11.3426
  },
  "Florence, IT": {
    "lat": 43.7696,
    "lon": 11.2558
  },
  "Bari, IT": {
    "lat": 41.1171,
    "lon": 16.8516
  },
  "Catania, IT": {
    "lat": 37.5079,
    "lon": 15.083
  },
  "Venice, IT": {
    "lat": 45.4408,
    "lon": 12.3155
  },
  "Verona, IT": {
    "lat": 45.4299,
    "lon": 10.9844
  },
  "Messina, IT": {
    "lat": 38.1938,
    "lon": 15.554
  },
  "Padua, IT": {
    "lat": 45.4064,
    "lon": 11.8768
  },
  "Trieste, IT": {
    "lat": 45.6495,
    "lon": 13.7768
  },
  "Taranto, IT": {
    "lat": 40.4644,
    "lon": 17.247
  },
  "Brescia, IT": {
    "lat": 45.5356,
    "lon": 10.2147
  },
  "Parma, IT": {
    "lat": 44.8015,
    "lon": 10.328
  },
  "Modena, IT": {
    "lat": 44.6478,
    "lon": 10.9252
  },
  "Reggio Calabria, IT": {
    "lat": 38.1113,
    "lon": 15.6473
  },
  "Perugia, IT": {
    "lat": 43.1107,
    "lon": 12.3908
  },
  "Livorno, IT": {
    "lat": 43.5426,
    "lon": 10.316
  },
  "Ravenna, IT": {
    "lat": 44.4184,
    "lon": 12.2039
  },
  "Cagliari, IT": {
    "lat": 39.2238,
    "lon": 9.1217
  },
  "Foggia, IT": {
    "lat": 41.4622,
    "lon": 15.5442
  },
  "Rimini, IT": {
    "lat": 44.0678,
    "lon": 12.5695
  },
  "Salerno, IT": {
    "lat": 40.682,
    "lon": 14.7684
  },
  "Ferrara, IT": {
    "lat": 44.8381,
    "lon": 11.6198
  },
  "Sassari, IT": {
    "lat": 40.7272,
    "lon": 8.5596
  },
  "Latina, IT": {
    "lat": 41.4661,
    "lon": 12.9043
  },
  "Giugliano in Campania, IT": {
    "lat": 40.9318,
    "lon": 14.195
  },
  "Monza, IT": {
    "lat": 45.5825,
    "lon": 9.2744
  },
  "Syracuse, IT": {
    "lat": 37.0755,
    "lon": 15.2866
  },
  "Pescara, IT": {
    "lat": 42.4618,
    "lon": 14.2161
  },
  "Bergamo, IT": {
    "lat": 45.6983,
    "lon": 9.67
  },
  "Trento, IT": {
    "lat": 46.0748,
    "lon": 11.1218
  },
  "Forlì, IT": {
    "lat": 44.2227,
    "lon": 12.0408
  },
  "Vicenza, IT": {
    "lat": 45.5573,
    "lon": 11.5409
  },
  "Terni, IT": {
    "lat": 42.5634,
    "lon": 12.6427
  },
  "Novara, IT": {
    "lat": 45.4469,
    "lon": 8.6218
  },
  "Piacenza, IT": {
    "lat": 45.0526,
    "lon": 9.6934
  },
  "Ancona, IT": {
    "lat": 43.5982,
    "lon": 13.5101
  },
  "Andria, IT": {
    "lat": 41.2312,
    "lon": 16.298
  },
  "Udine, IT": {
    "lat": 46.0619,
    "lon": 13.2372
  },
  "Arezzo, IT": {
    "lat": 43.4633,
    "lon": 11.88
  },
  "Cesena, IT": {
    "lat": 44.1391,
    "lon": 12.2463
  },
  "La Spezia, IT": {
    "lat": 44.1025,
    "lon": 9.8241
  },
  "Pisa, IT": {
    "lat": 43.7228,
    "lon": 10.3966
  },
  "Pistoia, IT": {
    "lat": 43.9306,
    "lon": 10.9237
  },
  "Lucca, IT": {
    "lat": 43.8437,
    "lon": 10.506
  },
  "Como, IT": {
    "lat": 45.8081,
    "lon": 9.0852
  },
  "Treviso, IT": {
    "lat": 45.6667,
    "lon": 12.2416
  },
  "Busto Arsizio, IT": {
    "lat": 45.6119,
    "lon": 8.8495
  },
  "Varese, IT": {
    "lat": 45.8206,
    "lon": 8.8251
  },
  "Sesto San Giovanni, IT": {
    "lat": 45.5349,
    "lon": 9.234
  },
  "Cinisello Balsamo, IT": {
    "lat": 45.5558,
    "lon": 9.221
  },
  "Casoria, IT": {
    "lat": 40.9075,
    "lon": 14.293
  },
  "Ragusa, IT": {
    "lat": 36.9257,
    "lon": 14.7306
  },
  "Asturias (Oviedo), ES": {
    "lat": 43.3619,
    "lon": -5.8494
  },
  "Biel/Bienne, CH": {
    "lat": 47.1368,
    "lon": 7.2461
  },
  "Lucerne, CH": {
    "lat": 47.0505,
    "lon": 8.3064
  },
  "St. Gallen, CH": {
    "lat": 47.4239,
    "lon": 9.3748
  },
  "Lugano, CH": {
    "lat": 46.0101,
    "lon": 8.96
  },
  "Fribourg, CH": {
    "lat": 46.8024,
    "lon": 7.1513
  },
  "Winterthur, CH": {
    "lat": 47.5056,
    "lon": 8.7241
  },
  "Lausanne, CH": {
    "lat": 46.5197,
    "lon": 6.6323
  },
  "Geneva, CH": {
    "lat": 46.2044,
    "lon": 6.1432
  },
  "Basel, CH": {
    "lat": 47.5596,
    "lon": 7.5886
  },
  "Bern, CH": {
    "lat": 46.9481,
    "lon": 7.4474
  },
  "Košice, SK": {
    "lat": 48.7167,
    "lon": 21.2581
  },
  "Prešov, SK": {
    "lat": 49.0017,
    "lon": 21.2394
  },
  "Žilina, SK": {
    "lat": 49.2231,
    "lon": 18.7393
  },
  "Banská Bystrica, SK": {
    "lat": 48.7363,
    "lon": 19.13
  },
  "Nitra, SK": {
    "lat": 48.3076,
    "lon": 18.0847
  },
  "Trnava, SK": {
    "lat": 48.3774,
    "lon": 17.5872
  },
  "Trenčín, SK": {
    "lat": 48.8945,
    "lon": 18.0444
  },
  "Poprad, SK": {
    "lat": 49.0614,
    "lon": 20.297
  },
  "Prievidza, SK": {
    "lat": 48.7745,
    "lon": 18.622
  },
  "Zvolen, SK": {
    "lat": 48.5744,
    "lon": 19.1258
  },
  "Debrecen, HU": {
    "lat": 47.5317,
    "lon": 21.6274
  },
  "Szeged, HU": {
    "lat": 46.253,
    "lon": 20.1414
  },
  "Miskolc, HU": {
    "lat": 48.1031,
    "lon": 20.7781
  },
  "Pécs, HU": {
    "lat": 46.0722,
    "lon": 18.2329
  },
  "Győr, HU": {
    "lat": 47.6833,
    "lon": 17.6351
  },
  "Nyíregyháza, HU": {
    "lat": 47.9554,
    "lon": 21.7167
  },
  "Kecskemét, HU": {
    "lat": 46.9062,
    "lon": 19.6917
  },
  "Székesfehérvár, HU": {
    "lat": 47.1899,
    "lon": 18.4103
  },
  "Split, HR": {
    "lat": 43.5089,
    "lon": 16.4392
  },
  "Rijeka, HR": {
    "lat": 45.3271,
    "lon": 14.4424
  },
  "Osijek, HR": {
    "lat": 45.5511,
    "lon": 18.6955
  },
  "Maribor, SI": {
    "lat": 46.5547,
    "lon": 15.6467
  },
  "Celje, SI": {
    "lat": 46.2309,
    "lon": 15.2604
  },
  "Kranj, SI": {
    "lat": 46.2389,
    "lon": 14.3556
  },
  "Varna, BG": {
    "lat": 43.2141,
    "lon": 27.9147
  },
  "Burgas, BG": {
    "lat": 42.5048,
    "lon": 27.4626
  },
  "Ruse, BG": {
    "lat": 43.8487,
    "lon": 25.9708
  },
  "Stara Zagora, BG": {
    "lat": 42.4258,
    "lon": 25.6342
  },
  "Pleven, BG": {
    "lat": 43.417,
    "lon": 24.6067
  },
  "Timișoara, RO": {
    "lat": 45.7489,
    "lon": 21.2087
  },
  "Iași, RO": {
    "lat": 47.1585,
    "lon": 27.6014
  },
  "Constanța, RO": {
    "lat": 44.1733,
    "lon": 28.6383
  },
  "Craiova, RO": {
    "lat": 44.3302,
    "lon": 23.7949
  },
  "Brașov, RO": {
    "lat": 45.6486,
    "lon": 25.6061
  },
  "Galați, RO": {
    "lat": 45.4369,
    "lon": 28.0503
  },
  "Ploiești, RO": {
    "lat": 44.9423,
    "lon": 26.0229
  },
  "Brăila, RO": {
    "lat": 45.2719,
    "lon": 27.9575
  },
  "Oradea, RO": {
    "lat": 47.0458,
    "lon": 21.9189
  },
  "Bacău, RO": {
    "lat": 46.5672,
    "lon": 26.9149
  },
  "Arad, RO": {
    "lat": 46.1833,
    "lon": 21.3167
  },
  "Pitești, RO": {
    "lat": 44.8565,
    "lon": 24.8697
  },
  "Sibiu, RO": {
    "lat": 45.7983,
    "lon": 24.1477
  },
  "Târgu Mureș, RO": {
    "lat": 46.5425,
    "lon": 24.5575
  },
  "Baia Mare, RO": {
    "lat": 47.6573,
    "lon": 23.5681
  },
  "Buzău, RO": {
    "lat": 45.149,
    "lon": 26.8232
  },
  "Satu Mare, RO": {
    "lat": 47.7993,
    "lon": 22.8731
  },
  "Râmnicu Vâlcea, RO": {
    "lat": 45.0997,
    "lon": 24.3695
  },
  "Drobeta-Turnu Severin, RO": {
    "lat": 44.6319,
    "lon": 22.6561
  },
  "Piatra Neamț, RO": {
    "lat": 46.9299,
    "lon": 26.3705
  },
  "Târgu Jiu, RO": {
    "lat": 45.0342,
    "lon": 23.2747
  },
  "Târgoviște, RO": {
    "lat": 44.9254,
    "lon": 25.4592
  },
  "Botoșani, RO": {
    "lat": 47.7487,
    "lon": 26.6597
  },
  "Cork, IE": {
    "lat": 51.8985,
    "lon": -8.4756
  },
  "Limerick, IE": {
    "lat": 52.6647,
    "lon": -8.6231
  },
  "Galway, IE": {
    "lat": 53.2707,
    "lon": -9.0568
  },
  "Waterford, IE": {
    "lat": 52.2583,
    "lon": -7.1119
  },
  "Tartu, EE": {
    "lat": 58.3806,
    "lon": 26.7251
  },
  "Narva, EE": {
    "lat": 59.3772,
    "lon": 28.1903
  },
  "Pärnu, EE": {
    "lat": 58.3859,
    "lon": 24.4971
  },
  "Daugavpils, LV": {
    "lat": 55.8749,
    "lon": 26.5362
  },
  "Liepāja, LV": {
    "lat": 56.5047,
    "lon": 21.0108
  },
  "Kaunas, LT": {
    "lat": 54.8985,
    "lon": 23.9036
  },
  "Klaipėda, LT": {
    "lat": 55.7033,
    "lon": 21.1443
  },
  "Šiauliai, LT": {
    "lat": 55.9349,
    "lon": 23.3135
  },
  "Gomel, BY": {
    "lat": 52.4345,
    "lon": 30.9754
  },
  "Mogilev, BY": {
    "lat": 53.9168,
    "lon": 30.3449
  },
  "Vitebsk, BY": {
    "lat": 55.1904,
    "lon": 30.2049
  },
  "Odesa, UA": {
    "lat": 46.4825,
    "lon": 30.7233
  },
  "Dnipro, UA": {
    "lat": 48.4647,
    "lon": 35.0462
  },
  "Donetsk, UA": {
    "lat": 48.0159,
    "lon": 37.8028
  },
  "Zaporizhzhia, UA": {
    "lat": 47.8229,
    "lon": 35.1903
  },
  "Kryvyi Rih, UA": {
    "lat": 47.9053,
    "lon": 33.3804
  },
  "Mykolaiv, UA": {
    "lat": 46.9659,
    "lon": 31.9974
  },
  "Mariupol, UA": {
    "lat": 47.0975,
    "lon": 37.5433
  },
  "Luhansk, UA": {
    "lat": 48.567,
    "lon": 39.3171
  },
  "Vinnytsia, UA": {
    "lat": 49.2328,
    "lon": 28.4809
  },
  "Sevastopol, UA": {
    "lat": 44.5888,
    "lon": 33.5224
  },
  "Simferopol, UA": {
    "lat": 44.9521,
    "lon": 34.1024
  },
  "Chernihiv, UA": {
    "lat": 51.4982,
    "lon": 31.2893
  },
  "Kherson, UA": {
    "lat": 46.6558,
    "lon": 32.6178
  },
  "Poltava, UA": {
    "lat": 49.5898,
    "lon": 34.5514
  },
  "Cherkasy, UA": {
    "lat": 49.4445,
    "lon": 32.0598
  },
  "Zhytomyr, UA": {
    "lat": 50.2649,
    "lon": 28.6767
  },
  "Sumy, UA": {
    "lat": 50.9077,
    "lon": 34.7981
  },
  "Rivne, UA": {
    "lat": 50.6199,
    "lon": 26.2516
  },
  "Ivano-Frankivsk, UA": {
    "lat": 48.9226,
    "lon": 24.7097
  },
  "Kropyvnytskyi, UA": {
    "lat": 48.5132,
    "lon": 32.2597
  },
  "Ternopil, UA": {
    "lat": 49.5534,
    "lon": 25.5948
  },
  "Luts’k, UA": {
    "lat": 50.7593,
    "lon": 25.3424
  },
  "Chernivtsi, UA": {
    "lat": 48.2915,
    "lon": 25.9351
  },
  "Uzhhorod, UA": {
    "lat": 48.6208,
    "lon": 22.2879
  },
  "Portsmouth, GB": {
    "lat": 50.8198,
    "lon": -1.088
  },
  "Leicester, GB": {
    "lat": 52.6369,
    "lon": -1.1398
  },
  "Coventry, GB": {
    "lat": 52.4066,
    "lon": -1.5127
  },
  "Bradford, GB": {
    "lat": 53.795,
    "lon": -1.7594
  },
  "Kingston upon Hull, GB": {
    "lat": 53.7446,
    "lon": -0.3353
  },
  "Plymouth, GB": {
    "lat": 50.3715,
    "lon": -4.1427
  },
  "Stoke-on-Trent, GB": {
    "lat": 53.004,
    "lon": -2.185
  },
  "Wolverhampton, GB": {
    "lat": 52.5862,
    "lon": -2.128
  },
  "Derby, GB": {
    "lat": 52.9228,
    "lon": -1.4766
  },
  "Swansea, GB": {
    "lat": 51.6214,
    "lon": -3.9436
  },
  "Aberdeen, GB": {
    "lat": 57.1497,
    "lon": -2.0943
  },
  "Dundee, GB": {
    "lat": 56.462,
    "lon": -2.9707
  },
  "Huddersfield, GB": {
    "lat": 53.6458,
    "lon": -1.785
  },
  "Poole, GB": {
    "lat": 50.719,
    "lon": -1.981
  },
  "Middlesbrough, GB": {
    "lat": 54.5742,
    "lon": -1.2348
  },
  "Blackpool, GB": {
    "lat": 53.8175,
    "lon": -3.035
  },
  "Bolton, GB": {
    "lat": 53.5833,
    "lon": -2.4333
  },
  "Ipswich, GB": {
    "lat": 52.0567,
    "lon": 1.149
  },
  "Telford, GB": {
    "lat": 52.6766,
    "lon": -2.443
  },
  "York, GB": {
    "lat": 53.9599,
    "lon": -1.0817
  },
  "West Bromwich, GB": {
    "lat": 52.5187,
    "lon": -1.9945
  },
  "Peterborough, GB": {
    "lat": 52.5695,
    "lon": -0.2405
  },
  "Stockport, GB": {
    "lat": 53.4106,
    "lon": -2.1576
  },
  "Brighton, GB": {
    "lat": 50.8225,
    "lon": -0.1372
  },
  "Slough, GB": {
    "lat": 51.5105,
    "lon": -0.5954
  },
  "Gloucester, GB": {
    "lat": 51.8642,
    "lon": -2.2383
  },
  "Watford, GB": {
    "lat": 51.6568,
    "lon": -0.3903
  },
  "Rotherham, GB": {
    "lat": 53.4301,
    "lon": -1.3568
  },
  "Cambridge, GB": {
    "lat": 52.2053,
    "lon": 0.1218
  },
  "Exeter, GB": {
    "lat": 50.7184,
    "lon": -3.5339
  },
  "Eastbourne, GB": {
    "lat": 50.768,
    "lon": 0.2848
  },
  "Sutton Coldfield, GB": {
    "lat": 52.5639,
    "lon": -1.8222
  },
  "Blackburn, GB": {
    "lat": 53.75,
    "lon": -2.4833
  },
  "Colchester, GB": {
    "lat": 51.8892,
    "lon": 0.9042
  },
  "Oldham, GB": {
    "lat": 53.5405,
    "lon": -2.1183
  },
  "St Helens, GB": {
    "lat": 53.4541,
    "lon": -2.7411
  },
  "Crawley, GB": {
    "lat": 51.113,
    "lon": -0.1831
  },
  "Wigan, GB": {
    "lat": 53.5444,
    "lon": -2.6311
  },
  "Lincoln, GB": {
    "lat": 53.2283,
    "lon": -0.5525
  },
  "Worcester, GB": {
    "lat": 52.1931,
    "lon": -2.221
  },
  "Wakefield, GB": {
    "lat": 53.6833,
    "lon": -1.5057
  },
  "Rochdale, GB": {
    "lat": 53.6177,
    "lon": -2.1576
  },
  "Basildon, GB": {
    "lat": 51.5684,
    "lon": 0.4578
  },
  "Solihull, GB": {
    "lat": 52.4128,
    "lon": -1.7781
  },
  "Southend-on-Sea, GB": {
    "lat": 51.5378,
    "lon": 0.7143
  },
  "Santa Ana, US": {
    "lat": 33.7455,
    "lon": -117.8677
  },
  "Santa Clarita, US": {
    "lat": 34.3917,
    "lon": -118.5426
  },
  "Garden Grove, US": {
    "lat": 33.7739,
    "lon": -117.9414
  },
  "Oceanside, US": {
    "lat": 33.1959,
    "lon": -117.3795
  },
  "Rancho Cucamonga, US": {
    "lat": 34.1064,
    "lon": -117.569
  },
  "Santa Rosa, US": {
    "lat": 38.4404,
    "lon": -122.7143
  },
  "Ontario, US": {
    "lat": 34.0633,
    "lon": -117.6509
  },
  "Lancaster, US": {
    "lat": 34.6868,
    "lon": -118.1542
  },
  "Palmdale, US": {
    "lat": 34.5794,
    "lon": -118.1165
  },
  "Salinas, US": {
    "lat": 36.6777,
    "lon": -121.6555
  },
  "Hayward, US": {
    "lat": 37.6688,
    "lon": -122.0808
  },
  "Pomona, US": {
    "lat": 34.0551,
    "lon": -117.7499
  },
  "Escondido, US": {
    "lat": 33.1192,
    "lon": -117.0864
  },
  "Sunnyvale, US": {
    "lat": 37.3688,
    "lon": -122.0363
  },
  "Torrance, US": {
    "lat": 33.8358,
    "lon": -118.3406
  },
  "Orange, US": {
    "lat": 33.7878,
    "lon": -117.8531
  },
  "Fullerton, US": {
    "lat": 33.8704,
    "lon": -117.9242
  },
  "Pasadena, US": {
    "lat": 34.1478,
    "lon": -118.1445
  },
  "Thousand Oaks, US": {
    "lat": 34.1706,
    "lon": -118.8371
  },
  "Simi Valley, US": {
    "lat": 34.2694,
    "lon": -118.7811
  },
  "Victorville, US": {
    "lat": 34.5361,
    "lon": -117.2912
  },
  "Santa Clara, US": {
    "lat": 37.3541,
    "lon": -121.9552
  },
  "Vallejo, US": {
    "lat": 38.1041,
    "lon": -122.2566
  },
  "Berkeley, US": {
    "lat": 37.8715,
    "lon": -122.273
  },
  "Fairfield, US": {
    "lat": 38.2494,
    "lon": -122.04
  },
  "Murrieta, US": {
    "lat": 33.5541,
    "lon": -117.2139
  },
  "Temecula, US": {
    "lat": 33.4936,
    "lon": -117.1484
  },
  "Antioch, US": {
    "lat": 38.0049,
    "lon": -121.8058
  },
  "West Covina, US": {
    "lat": 34.0686,
    "lon": -117.933
  },
  "Carlsbad, US": {
    "lat": 33.1581,
    "lon": -117.3506
  },
  "El Monte, US": {
    "lat": 34.0686,
    "lon": -118.0276
  },
  "Downey, US": {
    "lat": 33.94,
    "lon": -118.1332
  },
  "Costa Mesa, US": {
    "lat": 33.6411,
    "lon": -117.9187
  },
  "Jurupa Valley, US": {
    "lat": 34.0262,
    "lon": -117.4851
  },
  "Buena Park, US": {
    "lat": 33.8676,
    "lon": -117.9981
  },
  "Inglewood, US": {
    "lat": 33.9617,
    "lon": -118.3531
  },
  "Burbank, US": {
    "lat": 34.1808,
    "lon": -118.3089
  },
  "Santa Maria, US": {
    "lat": 34.953,
    "lon": -120.4357
  },
  "El Cajon, US": {
    "lat": 32.7948,
    "lon": -116.9625
  },
  "Rialto, US": {
    "lat": 34.1064,
    "lon": -117.3703
  },
  "Vacaville, US": {
    "lat": 38.3566,
    "lon": -121.9877
  },
  "Vista, US": {
    "lat": 33.2,
    "lon": -117.2425
  },
  "Hesperia, US": {
    "lat": 34.4264,
    "lon": -117.301
  },
  "Compton, US": {
    "lat": 33.8958,
    "lon": -118.2201
  },
  "Carson, US": {
    "lat": 33.8314,
    "lon": -118.282
  },
  "Westminster, US": {
    "lat": 33.7592,
    "lon": -117.9493
  },
  "Alhambra, US": {
    "lat": 34.0953,
    "lon": -118.127
  },
  "Santa Monica, US": {
    "lat": 34.0194,
    "lon": -118.4912
  },
  "San Mateo, US": {
    "lat": 37.563,
    "lon": -122.3255
  },
  "Daly City, US": {
    "lat": 37.6879,
    "lon": -122.4702
  },
  "Norwalk, US": {
    "lat": 33.9022,
    "lon": -118.0817
  },
  "Wichita Falls, US": {
    "lat": 33.9137,
    "lon": -98.4934
  },
  "Green Bay, US": {
    "lat": 44.5192,
    "lon": -88.0198
  },
  "West Valley City, US": {
    "lat": 40.6916,
    "lon": -112.001
  },
  "Clearwater, US": {
    "lat": 27.9659,
    "lon": -82.8
  },
  "Lakeland, US": {
    "lat": 28.0395,
    "lon": -81.9495
  },
  "Erie, US": {
    "lat": 42.1292,
    "lon": -80.0851
  },
  "Billings, US": {
    "lat": 45.7833,
    "lon": -108.5007
  },
  "Lewisville, US": {
    "lat": 33.0462,
    "lon": -96.9942
  },
  "Las Cruces, US": {
    "lat": 32.3199,
    "lon": -106.7636
  },
  "South Bend, US": {
    "lat": 41.6764,
    "lon": -86.25199
  },
  "College Station, US": {
    "lat": 30.6279,
    "lon": -96.3344
  },
  "Clovis, US": {
    "lat": 36.8252,
    "lon": -119.7029
  },
  "Richardson, US": {
    "lat": 32.9483,
    "lon": -96.7298
  },
  "Odessa, US": {
    "lat": 31.8457,
    "lon": -102.3676
  },
  "San Angelo, US": {
    "lat": 31.464,
    "lon": -100.437
  },
  "Pearland, US": {
    "lat": 29.5636,
    "lon": -95.286
  },
  "Tyler, US": {
    "lat": 32.3513,
    "lon": -95.3011
  },
  "Waco, US": {
    "lat": 31.5493,
    "lon": -97.1467
  },
  "Allen, US": {
    "lat": 33.1032,
    "lon": -96.6705
  },
  "League City, US": {
    "lat": 29.5075,
    "lon": -95.0949
  },
  "Sugar Land, US": {
    "lat": 29.6197,
    "lon": -95.6349
  },
  "Longview, US": {
    "lat": 32.5007,
    "lon": -94.7405
  },
  "Mission, US": {
    "lat": 26.2159,
    "lon": -98.3253
  },
  "Bryan, US": {
    "lat": 30.6744,
    "lon": -96.3697
  },
  "Baytown, US": {
    "lat": 29.7355,
    "lon": -94.9774
  },
  "Pharr, US": {
    "lat": 26.1948,
    "lon": -98.1836
  },
  "Missouri City, US": {
    "lat": 29.6186,
    "lon": -95.5377
  },
  "Temple, US": {
    "lat": 31.0982,
    "lon": -97.3428
  },
  "Harlingen, US": {
    "lat": 26.1906,
    "lon": -97.6961
  },
  "North Richland Hills, US": {
    "lat": 32.8343,
    "lon": -97.2289
  },
  "Victoria, US": {
    "lat": 28.8058,
    "lon": -97.0036
  },
  "Conroe, US": {
    "lat": 30.3119,
    "lon": -95.4561
  },
  "New Braunfels, US": {
    "lat": 29.703,
    "lon": -98.1245
  },
  "Mansfield, US": {
    "lat": 32.5632,
    "lon": -97.1417
  },
  "Cedar Park, US": {
    "lat": 30.5052,
    "lon": -97.8203
  },
  "Rowlett, US": {
    "lat": 32.9029,
    "lon": -96.5639
  },
  "Port Arthur, US": {
    "lat": 29.8852,
    "lon": -93.9423
  },
  "Euless, US": {
    "lat": 32.8371,
    "lon": -97.082
  },
  "Georgetown, US": {
    "lat": 30.6335,
    "lon": -97.6772
  },
  "Pflugerville, US": {
    "lat": 30.4395,
    "lon": -97.62
  },
  "San Marcos, US": {
    "lat": 29.8833,
    "lon": -97.9414
  },
  "Grapevine, US": {
    "lat": 32.9343,
    "lon": -97.0781
  }
};
