// scripts/buildGeoDb.mjs
import fs from "node:fs";
import path from "node:path";

const INPUT_FILE = path.join(process.cwd(), "data", "cities-eu-na.csv");
const OUTPUT_FILE = path.join(process.cwd(), "src", "utils", "geoBulk.js");

function build() {
  const raw = fs.readFileSync(INPUT_FILE, "utf8").trim();
  const lines = raw.split(/\r?\n/);

  if (lines.length <= 1) {
    console.error("CSV seems empty or only header.");
    process.exit(1);
  }

  // Read header row → ["city", "country_code", "lat", "lon"]
  const header = lines[0].split(",").map((h) => h.trim().toLowerCase());
  const idxCity    = header.indexOf("city");
  const idxCountry = header.indexOf("country_code");
  const idxLat     = header.indexOf("lat");
  const idxLon     = header.indexOf("lon");

  if (idxCity === -1 || idxCountry === -1 || idxLat === -1 || idxLon === -1) {
    console.error("CSV must have columns: city,country_code,lat,lon");
    process.exit(1);
  }

  const out = {};

  // Loop over each line after the header
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    const cols = line.split(",").map((c) => c.trim());

    const city    = cols[idxCity];
    const country = cols[idxCountry];
    const latStr  = cols[idxLat];
    const lonStr  = cols[idxLon];

    if (!city || !country || !latStr || !lonStr) continue;

    const lat = Number(latStr);
    const lon = Number(lonStr);
    if (Number.isNaN(lat) || Number.isNaN(lon)) continue;

    const key = `${city}, ${country}`;
    out[key] = { lat, lon };
  }

  // Turn `out` into a JavaScript file export
  const js = `// AUTO-GENERATED by scripts/buildGeoDb.mjs
// Do not edit by hand.

export const BULK_CITY_COORDS = ${JSON.stringify(out, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, js, "utf8");

  console.log(
    `Wrote ${Object.keys(out).length} city entries to ${OUTPUT_FILE}`
  );
}

build();
